name: Deploy Chatbot TutorKu

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Kode Terbaru
        uses: actions/checkout@v4

      - name: Sinkronisasi kode ke folder server
        run: |
          rsync -av --delete --exclude='.env' ./ /www/wwwroot/tutorku-py-chatbot/

      - name: Create or Update .env file
        run: |
          echo "${{ secrets.ENV_CONTENT }}" > /www/wwwroot/tutorku-py-chatbot/.env

      - name: Build dan Jalankan Docker
        run: |
          cd /www/wwwroot/tutorku-py-chatbot/
          docker compose up -d --build

      - name: Cleanup Sampah Docker
        run: |
          # Menghapus image bekas build lama yang sudah tidak dipakai (dangling)
          docker image prune -f
